### ISSUE TITLE
Add Support Coffe Lake

### ISSUE THREAD

**Issue by johnnync13** [stevezhengshiqi/one-key-cpufriend#1]
If you be able to add i7-8750h

**Comment by MisonL** [comment]
I hope my i7-4720HQ frequency can be reduced to 500MHZ.

**Comment by stevezhengshiqi** [comment]
Copy that. Custom frequency function would be added in the future.
@johnnync13 The script is using Apple's frequencyvectors in `X86PlatformPlugin.kext`. If the SMBIOS model can support your CPU, then the script works for you.
