### ISSUE TITLE
i78700报board-id不被支持。

### ISSUE THREAD

**Issue by ElkFly** [stevezhengshiqi/one-key-cpufriend#11]
你的board-id是 Mac-BE088AF8C5EB4FA2
[ ERROR ]: 抱歉，你的board-id暂不被支持!

**Comment by stevezhengshiqi** [comment]
我没有找到Mac-BE088AF8C5EB4FA2的plist(/System/Library/Extensions/IOPlatformPluginFamily.kext/Contents/PlugIns/X86PlatformPlugin.kext/Contents/Resources/Mac-BE088AF8C5EB4FA2.plist)中明确的LFM和EPP值，故不被支持。

**Comment by jay763190097** [comment]
@stevezhengshiqi board-id可以用freqVectorsEdit.sh改对吧？
我提示报错了

··
freqVectorsEdit.sh v3.2 Copyright (c) 2013-2020 by Pike R. Alpha.
-----------------------------------------------------------------
Bugs > https://github.com/Piker-Alpha/freqVectorsEdit.sh/issues <

./freqVectorsEdit.sh: line 1386: /Users/jay/Library/ssdtPRGen/Data/Models.cfg: No such file or directory
Available resource files (plists) with FrequencyVectors:

 [  1 ] Mac-EE2EBD4B90B839A8.plist (Unknown Model @ 3000 HWP/3200 HWP/3600 HWP)
 [  2 ] Mac-BE0E8AC46FE800CC.plist (Unknown Model @ 2400/2600/2900)
 [  3 ] Mac-42FD25EABCABB274.plist (Unknown Model)
 [  4 ] Mac-189A3D4F975D5FFC.plist (Unknown Model)
 [  5 ] Mac-90BE64C3CB5A9AEB.plist (Unknown Model @ 3000/3200/3600)
 [  6 ] Mac-BE088AF8C5EB4FA2.plist (Unknown Model)
 [  7 ] Mac-65CE76090165799A.plist (Unknown Model)
 [  8 ] Mac-6FEBD60817C77D8A.plist (Unknown Model @ 3800 HWP/4100 HWP)
 [  9 ] Mac-E43C1C25D4880AD6.plist (Unknown Model)
 [ 10 ] Mac-FA842E06C61E91C5.plist (Unknown Model)
 [ 11 ] Mac-FFE5EF870D7BA81A.plist (Unknown Model)
 [ 12 ] Mac-CAD6701F7CEA0921.plist (Unknown Model @ 3500 HWP/3700 HWP/4000 HWP)
 [ 13 ] Mac-226CB3C6A851A671.plist (Unknown Model @ 3600 HWP)
 [ 14 ] Mac-747B1AEFF11738BE.plist (Unknown Model @ 3000/3200/3600)
 [ 15 ] Mac-7DF21CB3ED6977E5.plist (Unknown Model)
 [ 16 ] Mac-4B682C642B45593E.plist (Unknown Model)
 [ 17 ] Mac-27AD2F918AE68F61.plist (Unknown Model HWP)
 [ 18 ] Mac-F305150B0C7DEEEF.plist (Unknown Model @ 2400/2600/2900)
 [ 19 ] Mac-7BA5B2DFE22DDD8C.plist (Unknown Model @ 3600 HWP/4000 HWP/4100 HWP/4500 HWP)
 [ 20 ] Mac-E7203C0F68AA0004.plist (Unknown Model @ 3900 HWP/4500 HWP)
 [ 21 ] Mac-63001698E7A34814.plist (Unknown Model @ 3600 HWP/4100 HWP/4600 HWP)
 [ 22 ] Mac-9F18E312C5C2BF0B.plist (Unknown Model @ 2700/3200)
 [ 23 ] Mac-112818653D3AABFC.plist (Unknown Model @ 3000/3200/3600)
 [ 24 ] Mac-031B6874CF7F642A.plist (Unknown Model)
 [ 25 ] Mac-112B0A653D3AAB9C.plist (Unknown Model @ 3000/3200/3600)
 [ 26 ] Mac-A5C67F76ED83108C.plist (Unknown Model @ 3500 HWP/3600 HWP/3800 HWP)
 [ 27 ] Mac-473D31EABEB93F9B.plist (Unknown Model @ 3100 HWP/3400 HWP)
 [ 28 ] Mac-77EB7D7DAF985301.plist (Unknown Model)
 [ 29 ] Mac-CF21D135A7D34AA6.plist (Unknown Model @ 3000/3200/3600)
 [ 30 ] Mac-53FDB3D8DB8CA971.plist (Unknown Model @ 3900 HWP/4500 HWP)
 [ 31 ] Mac-35C1E88140C3E6CF.plist (Unknown Model)
 [ 32 ] Mac-1E7E29AD0135F9BC.plist (Unknown Model @ 4100 HWP/4300 HWP/4500 HWP/4600 HWP/4800 HWP/5000 HWP)
 [ 33 ] Mac-9AE82516C7C6B903.plist (Unknown Model @ 2200 HWP/2700 HWP/3100 HWP)
 [ 34 ] Mac-7BA5B2D9E42DDD94.plist (Unknown Model)
 [ 35 ] Mac-937CB26E2E02BB01.plist (Unknown Model @ 2700/3200)
 [ 36 ] Mac-551B86E5744E2388.plist (Unknown Model @ 3800 HWP/3900 HWP/4100 HWP)
 [ 37 ] Mac-564FBA6031E5946A.plist (Unknown Model HWP)
 [ 38 ] Mac-B809C3757DA9BB8D.plist (Unknown Model)
 [ 39 ] Mac-9394BDF4BF862EE7.plist (Unknown Model @ 3000/3200/3600)
 [ 40 ] Mac-5F9802EFE386AA28.plist (Unknown Model @ 3800 HWP/4100 HWP)
 [ 41 ] Mac-35C5E08120C7EEAF.plist (Unknown Model @ 2700)
 [ 42 ] Mac-87DCB00F4AD77EEA.plist (Unknown Model @ 3200 HWP/3500 HWP/3800 HWP)
 [ 43 ] Mac-06F11F11946D27C5.plist (Unknown Model)
 [ 44 ] Mac-B4831CEBD52A0C4C.plist (Unknown Model @ 3400 HWP/4000 HWP)
 [ 45 ] Mac-DB15BD556843C820.plist (Unknown Model)
 [ 46 ] Mac-E1008331FDC96864.plist (Unknown Model @ 4500 HWP/4800 HWP/5000 HWP)
 [ 47 ] Mac-0CFF9C7C2B63DF8D.plist (Unknown Model @ 3200 HWP/3500 HWP/3800 HWP)
 [ 48 ] Mac-66E35819EE2D0D05.plist (Unknown Model @ 3300 HWP/3500 HWP/3600 HWP)
 [ 49 ] Mac-2BD1B31983FE1663.plist (Unknown Model)
 [ 50 ] Mac-50619A408DB004DA.plist (Unknown Model)
 [ 51 ] Mac-81E3E92DD6088272.plist (Unknown Model)
 [ 52 ] Mac-827FB448E656EC26.plist (Unknown Model @ 3800 HWP/4100 HWP/4200 HWP/4500 HWP/4700 HWP)
 [ 53 ] Mac-827FAC58A8FDFA22.plist (Unknown Model @ 3600 HWP)
 [ 54 ] Mac-3CBD00234E554E41.plist (Unknown Model)
 [ 55 ] Mac-A369DDC4E67F1C45.plist (Unknown Model)
 [ 56 ] Mac-937A206F2EE63C01.plist (Unknown Model @ 4100 HWP/4300 HWP/4500 HWP/4600 HWP/4800 HWP/5000 HWP)
 [ 57 ] Mac-77F17D7DA9285301.plist (Unknown Model)
 [ 58 ] Mac-06F11FD93F0323C5.plist (Unknown Model)
 [ 59 ] Mac-27ADBB7B4CEE8E61.plist (Unknown Model)
 [ 60 ] Mac-4BFBC784B845591E.plist (Unknown Model)
 [ 61 ] Mac-AA95B1DDAB278B95.plist (Unknown Model @ 4100 HWP/4300 HWP/4600 HWP/5000 HWP)

Please choose the desired plist for your hardware (Exit/1-61) ? 48

Patching LFM from: 1300 MHz to 800 MHz

Triggering a kernelcache refresh ...
touch: /System/Library/Extensions: Read-only file system

Do you want to open Mac-3CBD00234E554E41.plist (y/n)? n
Do you want to reboot now? (y/n) n·
··
