### ISSUE TITLE
能增加19.1机型吗

### ISSUE THREAD

**Issue by qin9125** [stevezhengshiqi/one-key-cpufriend#14]
我很想直接19.1机型里有4组数据，脚本修改的是哪一组呢？然后生成，谢谢博主

**Comment by stevezhengshiqi** [comment]
iMac19,1 里的frenquencyVector并没有LFM和EPP，不属于常规机型，故不能直接修改。

**Comment by 1900forever** [comment]
我的也是19,1，用的是9900k的CPU，Mac-AA95B1DDAB278B95，提示抱歉，你的board-id暂不被支持

**Comment by stevezhengshiqi** [comment]
iMac19,1 机型不能被支持。
