### ISSUE TITLE
When I ran the provided script, it gave this error [ ERROR ]: Failed to retrieve latest release from https://api.github.com/repos/acidanthera/CPUFriend/releases/latest, please check your connection!

### ISSUE THREAD

**Issue by skandavc18** [stevezhengshiqi/one-key-cpufriend#15]

**Comment by stevezhengshiqi** [comment]
As the prompt says, it is a network issue. Please make sure your network service can access apt.github.com without problems.

**Comment by skandavc18** [comment]
Even with a good network, I am still getting that error

**Comment by stevezhengshiqi** [comment]
Well, that's something I am not able to fix. In the script, it uses `curl` command to obtain the latest release number. It seems that your device didn't pass this command:
```
curl --silent https://api.github.com/repos/acidanthera/CPUFriend/releases/latest | grep 'tag_name' | head -n 1 | awk -F ":" '{print $2}' | tr -d '"' | tr -d ',' | tr -d ' '
```

You could try this command or ping api.github.com to check the network quality.
