### ISSUE TITLE
[BUG]: generated CPUFriendDataProvider.kexts for each performance setting are all the exact same

### ISSUE THREAD

**Issue by LeeBinder** [stevezhengshiqi/one-key-cpufriend#16]
I just created a CPUFriendDataProvider.kext for MacBookPro15,4 for each performance setting (always moved generated CPUFriendDataProvider.kext away from Desktop into a newly created folder whose name matches the chosen performance setting), extracted the cf-frequency-data string from each Info.plist inside each kext, saved as txt files with names matching the performance, and cross-compared all 4 with Beyond Compare text compare mode. Result: THEY ARE ALL THE EXACT SAME, or in other words, the script does NOT work (at least not for model 15,4).

- macOS Mojave 10.14.6 with latest security update
- latest Clover, all latest kexts
- no FakeCPUID argument in config.plist
- IOPlatformPluginFamily.kext
- Lilu is working
- correct SMBIOS model
- plugin-type=1
- [config.plist](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/blob/master/EFI/CLOVER/config.plist)

[CPUFriendDataProvider for MacBookPro15,4 with stevezhengshiqi's one-key-cpufriend.zip](https://github.com/stevezhengshiqi/one-key-cpufriend/files/4204712/CPUFriendDataProvider.for.MacBookPro15.4.with.stevezhengshiqi.s.one-key-cpufriend.zip)

**Comment by LeeBinder** [comment]
oh, I guess it's because I accidentally already had another mod of CPUFriendDataProvider installed ...

I'll re-test ASAP (might not be tomorrow). For now just disregard my issue report :|

**Comment by LeeBinder** [comment]
@stevezhengshiqi I just re-checked it on a vanilla OS: the script is NOT working - producing the exact same strings from [(1) Max Power Saving] .. (2)..(3) .. (4) Performance]. I always chose (2) 800mhz.

I don't have any more time to invest into this and can't debug if the bug is in your part of the script, or in the downloaded part.

Any idea?

**Comment by stevezhengshiqi** [comment]
I didn't notice that. Thank you so much for reporting this issue.

**Comment by LeeBinder** [comment]
Great Steve that you found the problematic line and fixed it so quickly! I can confirm the strings now look different for each performance for MBP15,4:

(1) Max Power Saving:			77 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 4**4**

(2) Balance Power (Default):	77 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 4**3**

(3) Balance performance:		77 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 4**2**

(4) Performance:						77 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 4**1**

:+1:

**Comment by LeeBinder** [comment]
@stevezhengshiqi sorry, but same thing with MacBookAir8,2 - all strings are the same .. :(

**Comment by stevezhengshiqi** [comment]
@LeeBinder Hi, I am pretty sure that the script is effective on Mac-226CB3C6A851A671(MBA8,2). Could you have a recheck on that?

**Comment by LeeBinder** [comment]
@stevezhengshiqi : this must most likely be a bug in the most recent Beyond Compare app which shows me the expected diffs in the same files in Catalina but not in Mojave - sorry about the false alert!

MacBookAir8,2 Mac-226CB3C6A851A671 CPUFriendDataProvider

via stevezhengshiqi's one-key-cpufriend:

in Catalina with kexts via Clover/kexts/Other

(1) Max Power Saving:				0A 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 44

(2) Balance Power (Default):	0A 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 43

(3) Balance performance:		0A 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 42

(4) Performance:						0A 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
