### ISSUE TITLE
你好，请问这里为什么没有执行changeEPP函数中的内容

### ISSUE THREAD

**Issue by vihor3** [stevezhengshiqi/one-key-cpufriend#17]
如果所示：
![运行截图](https://i.loli.net/2020/02/20/PQAHuBq8VktDoXz.png)

**Comment by stevezhengshiqi** [comment]
@vihor3 你好，MacBookPro12,1 这个机型的变频文件里我没有发现有关EPP值的键值。这个情况发生在很多5代U的机型上。针对这些机型，我个人推荐使用https://github.com/Piker-Alpha/ssdtPRGen.sh 来生成变频参数。
