### ISSUE TITLE
CPUFriendDataProvider.kext not loading

### ISSUE THREAD

**Issue by robi62** [stevezhengshiqi/one-key-cpufriend#20]
Hi I have used your script for my Kabylake i37100u and although cpu frequency has dropped to 800mhz from 1000 which it was before when I run kextstat in terminal is not loaded the other kext cpufrien loads fine….
Any ideas???
If you need any more info let me know.
By the way awesome job with the script for making it easier for newbies like me

**Comment by stevezhengshiqi** [comment]
@robi62 Glad you like it. CPUFriendDataProvider.kext is only a plist injector, so it's normal that it doesn't show in kextstat.

**Comment by robi62** [comment]
I see just a question my p states according to applecpuinfo kext are as follow but hwmontor and stat only seem to show only a few is this normal for new cpu??
Great work anyway

CPU Ratio Info:
------------------------------------
CPU Low Frequency Mode.............: 400 MHz
CPU Maximum non-Turbo Frequency....: 2400 MHz
CPU Maximum Turbo Frequency........: 2400 MHz

IGPU Info:
------------------------------------
IGPU Current Frequency.............:    0 MHz
IGPU Minimum Frequency.............:  300 MHz
IGPU Maximum Non-Turbo Frequency...:  300 MHz
IGPU Maximum Turbo Frequency.......: 1000 MHz
IGPU Maximum limit.................: No Limit

CPU P-States [ (8) 20 24 ] iGPU P-States [ ]
CPU P-States [ 8 11 (20) 24 ] iGPU P-States [ ]
CPU P-States [ 8 11 15 (20) 24 ] iGPU P-States [ ]
CPU P-States [ (8) 10 11 15 20 24 ] iGPU P-States [ ]
CPU P-States [ (8) 10 11 15 16 20 24 ] iGPU P-States [ ]
CPU P-States [ (8) 10 11 15 16 18 20 24 ] iGPU P-States [ ]
CPU P-States [ (8) 9 10 11 15 16 18 20 24 ] iGPU P-States [ ]
CPU P-States [ (8) 9 10 11 13 15 16 18 20 24 ] iGPU P-States [ ]
CPU P-States [ (8) 9 10 11 12 13 15 16 18 20 24 ] iGPU P-States [ ]
CPU P-States [ (8) 9 10 11 12 13 15 16 18 20 22 24 ] iGPU P-States [ ]
CPU P-States [ (8) 9 10 11 12 13 15 16 17 18 20 22 24 ] iGPU P-States [ ]
CPU P-States [ (8) 9 10 11 12 13 14 15 16 17 18 20 22 24 ] iGPU P-States [ ]
CPU P-States [ 8 9 10 11 12 13 14 15 16 17 18 19 (20) 22 24 ] iGPU P-States [ ]
CPU P-States [ 8 9 10 11 12 13 14 15 16 17 18 19 20 22 (24) ] iGPU P-States [ (18) ]
bash-3.2#

**Comment by stevezhengshiqi** [comment]
Sorry that I have no idea about this.
