### ISSUE TITLE
Sometimes battery drain too fast

### ISSUE THREAD

**Issue by nikhil19rathore99** [stevezhengshiqi/one-key-cpufriend#21]
I've used cpufriend from pm's pikers scipt method but my battery drains too fast 
Will it possible to make longer battery life from your cpu provider kext 
I've used manjaro linux alongside with mac it gives me 4hr+ battery on browsing and normal work but on mac it won't give me a even 2.3hr
Will it be possible to get more battery life on normal work
System specs: 
Asus X556UQK
Processor: i5-7200U
Ram: 8GB
Thanks

**Comment by nikhil19rathore99** [comment]
[EFI.zip](https://github.com/stevezhengshiqi/one-key-cpufriend/files/4851518/EFI.zip)
I'll share my EFI to you so you better understand the which CPU provider kext i used??
Help me to get better battery management
also one more thing
It says service recommended
![Screenshot 2020-06-30 at 5 11 23 PM](https://user-images.githubusercontent.com/32436513/86122317-43795380-baf5-11ea-96a0-f7264c1ff0e9.png)

**Comment by nikhil19rathore99** [comment]
> [EFI.zip](https://github.com/stevezhengshiqi/one-key-cpufriend/files/4851518/EFI.zip)
> I'll share my EFI to you so you better understand the which CPU provider kext i used??
> Help me to get better battery management
> also one more thing
> It says service recommended
> ![Screenshot 2020-06-30 at 5 11 23 PM](https://user-images.githubusercontent.com/32436513/86122317-43795380-baf5-11ea-96a0-f7264c1ff0e9.png)

Can u help me to build openCore for my laptop model if possible i've tried by myself but not able to got success ??

**Comment by stevezhengshiqi** [comment]
@nikhil19rathore99 Your X86PlatformPlugin.kext is not loading, try to remove `CPUFriend.kext`, `CPUFriendDataProvider.kext`, and `CpuTscSync.kext`. For modern platform laptops, pikers script is no longer needed. Just choose a correct SMBIOS will bring great power control.

**Comment by nikhil19rathore99** [comment]
> @nikhil19rathore99 Your X86PlatformPlugin.kext is not loading, try to remove `CPUFriend.kext`, `CPUFriendDataProvider.kext`, and `CpuTscSync.kext`. For modern platform laptops, pikers script is no longer needed. Just choose a correct SMBIOS will bring great power control.

Without cputcsync i am not able to go to the login because it was stuck at login like graphics stucks

**Comment by nikhil19rathore99** [comment]
> > @nikhil19rathore99 Your X86PlatformPlugin.kext is not loading, try to remove `CPUFriend.kext`, `CPUFriendDataProvider.kext`, and `CpuTscSync.kext`. For modern platform laptops, pikers script is no longer needed. Just choose a correct SMBIOS will bring great power control.
> 
> Without cputcsync i am not able to go to the login because it was stuck at login like graphics stucks

About SMBIOS which one should i use 14,2 or any other

**Comment by stevezhengshiqi** [comment]
14,1 is good. Get rid of CPUFriendDataProvider you may see different Energy Saver panel.

**Comment by nikhil19rathore99** [comment]
![Screenshot 2020-07-01 at 11 01 41 AM](https://user-images.githubusercontent.com/32436513/86206538-41150900-bb8a-11ea-91b3-057e7beec4af.png
Will i get better battery management now??
Please look at it i've attached  Ioreg of my mac

[Asus_X556UQK.zip](https://github.com/stevezhengshiqi/one-key-cpufriend/files/4855869/Asus_X556UQK.zip)

**Comment by stevezhengshiqi** [comment]
Looks better to me, at least X86PlugInFamily is loaded according to your ioreg. More PM information can be found by running AppleIntelInfo.kext

**Comment by nikhil19rathore99** [comment]
> Looks better to me, at least X86PlugInFamily is loaded according to your ioreg. More PM information can be found by running AppleIntelInfo.kext

now 2% drop in 1.3 min, that is too fast.

**Comment by nikhil19rathore99** [comment]
> > Looks better to me, at least X86PlugInFamily is loaded according to your ioreg. More PM information can be found by running AppleIntelInfo.kext
> 
> now 2% drop in 1.3 min, that is too fast.

**Comment by nikhil19rathore99** [comment]
> Looks better to me, at least X86PlugInFamily is loaded according to your ioreg. More PM information can be found by running AppleIntelInfo.kext

Sorry Bymistake i close it please reopen it and how i get the info from AppleIntelInfo

**Comment by nikhil19rathore99** [comment]
AppleIntelInfo attached below:
AppleIntelInfo.kext v2.4 Copyright © 2012-2017 Pike R. Alpha. All rights reserved.

Settings:
------------------------------------------
logMSRs..................................: 1
logIGPU..................................: 1
logCStates...............................: 1
logIPGStyle..............................: 1
InitialTSC...............................: 0x933b08122d5 (374 MHz)
MWAIT C-States...........................: 286531872

Processor Brandstring....................: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

Processor Signature..................... : 0x806E9
------------------------------------------
 - Family............................... : 6
 - Stepping............................. : 9
 - Model................................ : 0x8E (142)

Model Specific Registers (MSRs)
------------------------------------------

MSR_CORE_THREAD_COUNT............(0x35)  : 0x1B
------------------------------------------
 - Core Count........................... : 2
 - Thread Count......................... : 4

MSR_PLATFORM_INFO................(0xCE)  : 0x4043DF1011B00
------------------------------------------
 - Maximum Non-Turbo Ratio.............. : 0x1B (2700 MHz)
 - Ratio Limit for Turbo Mode........... : 1 (programmable)
 - TDP Limit for Turbo Mode............. : 1 (programmable)
 - Low Power Mode Support............... : 1 (LPM supported)
 - Number of ConfigTDP Levels........... : 2 (additional TDP level(s) available)
 - Maximum Efficiency Ratio............. : 4
 - Minimum Operating Ratio.............. : 4

MSR_PMG_CST_CONFIG_CONTROL.......(0xE2)  : 0x1E008006
------------------------------------------
 - I/O MWAIT Redirection Enable......... : 0 (not enabled)
 - CFG Lock............................. : 1 (MSR locked until next reset)
 - C3 State Auto Demotion............... : 1 (enabled)
 - C1 State Auto Demotion............... : 1 (enabled)
 - C3 State Undemotion.................. : 1 (enabled)
 - C1 State Undemotion.................. : 1 (enabled)
 - Package C-State Auto Demotion........ : 0 (disabled/unsupported)
 - Package C-State Undemotion........... : 0 (disabled/unsupported)

MSR_PMG_IO_CAPTURE_BASE..........(0xE4)  : 0x51814
------------------------------------------
 - LVL_2 Base Address................... : 0x1814
 - C-state Range........................ : 5 (C-States not included, I/O MWAIT redirection not enabled)

IA32_MPERF.......................(0xE7)  : 0x16E777038AC
IA32_APERF.......................(0xE8)  : 0x146D5483970

MSR_FLEX_RATIO...................(0x194) : 0x0
------------------------------------------

MSR_IA32_PERF_STATUS.............(0x198) : 0x1D1100001900
------------------------------------------
 - Current Performance State Value...... : 0x1900 (2500 MHz)

MSR_IA32_PERF_CONTROL............(0x199) : 0xA00
------------------------------------------
 - Target performance State Value....... : 0xA00 (1000 MHz)
 - Intel Dynamic Acceleration........... : 0 (IDA engaged)

IA32_CLOCK_MODULATION............(0x19A) : 0x0

IA32_THERM_INTERRUPT.............(0x19B) : 0x10
------------------------------------------
 - High-Temperature Interrupt Enable.... : 0 (disabled)
 - Low-Temperature Interrupt Enable..... : 0 (disabled)
 - PROCHOT# Interrupt Enable............ : 0 (disabled)
 - FORCEPR# Interrupt Enable............ : 0 (disabled)
 - Critical Temperature Interrupt Enable : 1 (enabled)
 - Threshold #1 Value................... : 0
 - Threshold #1 Interrupt Enable........ : 0 (disabled)
 - Threshold #2 Value................... : 0
 - Threshold #2 Interrupt Enable........ : 0 (disabled)
 - Power Limit Notification Enable...... : 0 (disabled)

IA32_THERM_STATUS................(0x19C) : 0x882F0800
------------------------------------------
 - Thermal Status....................... : 0
 - Thermal Log.......................... : 0
 - PROCHOT # or FORCEPR# event.......... : 0
 - PROCHOT # or FORCEPR# log............ : 0
 - Critical Temperature Status.......... : 0
 - Critical Temperature log............. : 0
 - Thermal Threshold #1 Status.......... : 0
 - Thermal Threshold #1 log............. : 0
 - Thermal Threshold #2 Status.......... : 0
 - Thermal Threshold #2 log............. : 0
 - Power Limitation Status.............. : 0
 - Power Limitation log................. : 1
 - Current Limit Status................. : 0
 - Current Limit log.................... : 0
 - Cross Domain Limit Status............ : 0
 - Cross Domain Limit log............... : 0
 - Digital Readout...................... : 47
 - Resolution in Degrees Celsius........ : 1
 - Reading Valid........................ : 1 (valid)

MSR_THERM2_CTL...................(0x19D) : 0x0

IA32_MISC_ENABLES................(0x1A0) : 0x850089
------------------------------------------
 - Fast-Strings......................... : 1 (enabled)
 - FOPCODE compatibility mode Enable.... : 0
 - Automatic Thermal Control Circuit.... : 1 (enabled)
 - Split-lock Disable................... : 0
 - Performance Monitoring............... : 1 (available)
 - Bus Lock On Cache Line Splits Disable : 0
 - Hardware prefetch Disable............ : 0
 - Processor Event Based Sampling....... : 0 (PEBS supported)
 - GV1/2 legacy Enable.................. : 0
 - Enhanced Intel SpeedStep Technology.. : 1 (enabled)
 - MONITOR FSM.......................... : 1 (MONITOR/MWAIT supported)
 - Adjacent sector prefetch Disable..... : 0
 - CFG Lock............................. : 0 (MSR not locked)
 - xTPR Message Disable................. : 1 (disabled)

MSR_TEMPERATURE_TARGET...........(0x1A2) : 0xA640000
------------------------------------------
 - Turbo Attenuation Units.............. : 0 
 - Temperature Target................... : 100
 - TCC Activation Offset................ : 10

MSR_MISC_PWR_MGMT................(0x1AA) : 0x401CC1
------------------------------------------
 - EIST Hardware Coordination........... : 1 (hardware coordination disabled)
 - Energy/Performance Bias support...... : 1
 - Energy/Performance Bias.............. : 0 (disabled/MSR not visible to software)
 - Thermal Interrupt Coordination Enable : 1 (thermal interrupt routed to all cores)

MSR_TURBO_RATIO_LIMIT............(0x1AD) : 0x1F1F1F1F
------------------------------------------
 - Maximum Ratio Limit for C01.......... : 1F (3100 MHz) 
 - Maximum Ratio Limit for C02.......... : 1F (3100 MHz) 

IA32_ENERGY_PERF_BIAS............(0x1B0) : 0x0

MSR_POWER_CTL....................(0x1FC) : 0x24005F
------------------------------------------
 - Bi-Directional Processor Hot..........: 1 (enabled)
 - C1E Enable............................: 1 (enabled)

MSR_RAPL_POWER_UNIT..............(0x606) : 0xA0E03
------------------------------------------
 - Power Units.......................... : 3 (1/8 Watt)
 - Energy Status Units.................. : 14 (61 micro-Joules)
 - Time Units .......................... : 10 (976.6 micro-Seconds)

MSR_PKG_POWER_LIMIT..............(0x610) : 0x4280C800DD80C8
------------------------------------------
 - Package Power Limit #1............... : 25 Watt
 - Enable Power Limit #1................ : 1 (enabled)
 - Package Clamping Limitation #1....... : 1 (allow going below OS-requested P/T state during Time Window for Power Limit #1)
 - Time Window for Power Limit #1....... : 110 (163840 milli-Seconds)
 - Package Power Limit #2............... : 25 Watt
 - Enable Power Limit #2................ : 1 (enabled)
 - Package Clamping Limitation #2....... : 0 (disabled)
 - Time Window for Power Limit #2....... : 33 (10 milli-Seconds)
 - Lock................................. : 0 (MSR not locked)

MSR_PKG_ENERGY_STATUS............(0x611) : 0xD9D06D0
------------------------------------------
 - Total Energy Consumed................ : 13940 Joules (Watt = Joules / seconds)

MSR_PP1_POWER_LIMIT..............(0x640) : 0x0

MSR_PP1_ENERGY_STATUS............(0x641) : 0x3C1206
------------------------------------------
 - Total Energy Consumed................ : 240 Joules (Watt = Joules / seconds)

MSR_PP1_POLICY...................(0x642) : 0x18
------------------------------------------
 - Priority Level....................... : 24

MSR_CONFIG_TDP_NOMINAL...........(0x648) : 0x19
MSR_CONFIG_TDP_LEVEL1............(0x649) : 0x8003C
MSR_CONFIG_TDP_LEVEL2............(0x64a) : 0x1B00C8
MSR_CONFIG_TDP_CONTROL...........(0x64b) : 0x0
MSR_TURBO_ACTIVATION_RATIO.......(0x64c) : 0x0
MSR_PKGC3_IRTL...................(0x60a) : 0x884E
MSR_PKGC6_IRTL...................(0x60b) : 0x8876
MSR_PKGC7_IRTL...................(0x60c) : 0x8894
MSR_PKG_C2_RESIDENCY.............(0x60d) : 0x146C995B720
MSR_PKG_C3_RESIDENCY.............(0x3f8) : 0x4FEC78B540D
MSR_PKG_C2_RESIDENCY.............(0x60d) : 0x146C9C24979
MSR_PKG_C3_RESIDENCY.............(0x3f8) : 0x4FEC78B540D
MSR_PKG_C6_RESIDENCY.............(0x3f9) : 0x0
MSR_PKG_C7_RESIDENCY.............(0x3fa) : 0x0

MSR_PLATFORM_ENERGY_COUNTER......(0x64D) : 0x732FE15 
------------------------------------------

MSR_PPERF........................(0x64E) : 0x132DFFE3A66
------------------------------------------
 - Hardware workload scalability........ : 1318017972838

MSR_CORE_PERF_LIMIT_REASONS......(0x64F) : 0x8000000
------------------------------------------
 - PROCHOT Status....................... : 0
 - Thermal Status....................... : 0
 - Residency State Regulation Status.... : 0
 - Running Average Thermal Limit Status. : 0
 - VR Therm Alert Status................ : 0
 - VR Therm Design Current Status....... : 0
 - Other Status......................... : 0
 - Package/Platform-Level #1 Power Limit : 0
 - Package/Platform-Level #2 Power Limit : 0
 - Max Turbo Limit Status............... : 0
 - Turbo Transition Attenuation Status.. : 0
 - PROCHOT Log.......................... : 0
 - Thermal Log.......................... : 0
 - Residency State Regulation Log....... : 0
 - Running Average Thermal Limit Log.... : 0
 - VR Therm Alert Log................... : 0
 - VR Thermal Design Current Log........ : 0
 - Other Status Log..................... : 0
 - Package/Platform-Level #1 Power Limit : 0
 - Package/Platform-Level #2 Power Limit : 1 (status bit has asserted)
 - Max Turbo Limit Log.................. : 0
 - Turbo Transition Attenuation Log..... : 0
HDC Supported

IA32_PKG_HDC_CTL.................(0xDB0) : 0x0

IA32_PM_CTL1.....................(0xDB1) : 0x1
------------------------------------------
HDC Allow Block..................(0xDB1) : 1 (HDC blocked)

IA32_THREAD_STALL................(0xDB2) : 0x0

MSR_PKG_HDC_CONFIG...............(0x652) : 0x2
------------------------------------------
Pkg Cx Monitor ..................(0x652) : 2 (count package C3 and deeper)
MSR_CORE_HDC_RESIDENCY...........(0x653) : 0x0

MSR_PKG_HDC_SHALLOW_RESIDENCY....(0x655) : 0x0

MSR_PKG_HDC_DEEP_RESIDENCY.......(0x656) : 0x0

IA32_TSC_DEADLINE................(0x6E0) : 0x933CE4E3E6E
MSR_PPERF........................(0x63E) : 0x1 (22)

IA32_PM_ENABLE...................(0x770) : 0x1 (HWP Supported and Enabled)

IA32_HWP_CAPABILITIES............(0x771) : 0x106191F
-----------------------------------------
 - Highest Performance.................. : 31
 - Guaranteed Performance............... : 25
 - Most Efficient Performance........... : 6
 - Lowest Performance................... : 1

IA32_HWP_INTERRUPT...............(0x773) : 0x1
------------------------------------------
 - Guaranteed Performance Change........ : 1 (Interrupt generated on change of)
 - Excursion Minimum.................... : 0 (Interrupt generation disabled)

IA32_HWP_REQUEST................(0x774) : 0x80191F04
-----------------------------------------
 - Minimum Performance................. : 4
 - Maximum Performance................. : 31
 - Desired Performance................. : 25
 - Energy Efficient Performance........ : 128
 - Activity Window..................... : 0, 0
 - Package Control..................... : 0

IA32_HWP_STATUS..................(0x777) : 0x0
-----------------------------------------
 - Guaranteed Performance Change....... : 0 (has not occured)
 - Excursion To Minimum................ : 0 (has not occured)

CPU Ratio Info:
------------------------------------------
Base Clock Frequency (BLCK)............. : 100 MHz
Maximum Efficiency Ratio/Frequency.......:  4 ( 400 MHz)
Maximum non-Turbo Ratio/Frequency........: 27 (2700 MHz)
Maximum Turbo Ratio/Frequency............: 31 (3100 MHz)

IGPU Info:
------------------------------------------
IGPU Current Frequency...................:    0 MHz
IGPU Minimum Frequency...................:  300 MHz
IGPU Maximum Non-Turbo Frequency.........:  300 MHz
IGPU Maximum Turbo Frequency.............: 1000 MHz
IGPU Maximum limit.......................: No Limit

P-State ratio * 100 = Frequency in MHz
------------------------------------------
CPU P-States [ (13) 23 31 ] iGPU P-States [ ]
CPU C3-Cores [ 0 1 2 3 ]
CPU C7-Cores [ 0 1 2 3 ]
CPU P-States [ (13) 23 31 ] iGPU P-States [ ]
CPU P-States [ (13) 23 24 31 ] iGPU P-States [ ]
CPU P-States [ 13 (20) 23 24 31 ] iGPU P-States [ ]
CPU P-States [ 13 (20) 23 24 31 ] iGPU P-States [ (18) ]
CPU P-States [ 13 20 23 24 (25) 31 ] iGPU P-States [ 18 ]
CPU P-States [ (4) 13 20 23 24 25 31 ] iGPU P-States [ 18 ]

**Comment by nikhil19rathore99** [comment]
Please look at it, if it can be improved
