### ISSUE TITLE
problem with CPUFriend file

### ISSUE THREAD

**Issue by alexdelli** [stevezhengshiqi/one-key-cpufriend#24]
This is the problem after the command in terminal:

unzip:  cannot find zipfile directory in one of CPUFriend-https-RELEASE.zip or
        CPUFriend-https-RELEASE.zip.zip, and cannot find CPUFriend-https-RELEASE.zip.ZIP, period.

At the end of the procedure, only the file CPUFriendDataProvider is generated. CPUFriend no

thank you

**Comment by stevezhengshiqi** [comment]
Would you re-run the script? This problem does not happen at my side. It seems like the script fails to get a valid version number from https://github.com/acidanthera/CPUFriend/releases.

**Comment by alexdelli** [comment]
Now it works.... mmmmmm.
thank you and sorry for the time lost
