### ISSUE TITLE
CPUFriend should support 10.8+

### ISSUE THREAD

**Issue by PMheart** [stevezhengshiqi/one-key-cpufriend#26]
Hello,

In README I saw MinKernel is set to 15.0.0, which indicates the minimum macOS version 11.0 (El Capitan). However, CPUFriend supports even older distributions as can be seen [here](https://github.com/acidanthera/CPUFriend/blob/9517c414b5ad98342a0662b930fa35c2d0e648ac/CPUFriend/kern_start.cpp#L37) and [there](https://github.com/acidanthera/CPUFriend/blob/9517c414b5ad98342a0662b930fa35c2d0e648ac/CPUFriend/Info.plist#L67-L78). You already have checks for supported models, I guess it can be a good idea to lower MinKernel to 12.0.0, or rather leave it empty as CPUFriend and Lilu can handle version matching.

Thanks,
PMheart

**Comment by stevezhengshiqi** [comment]
Thank you little cat.
