### ISSUE TITLE
性能模式选择时设置的默认模式无效

### ISSUE THREAD

**Issue by athlonreg** [stevezhengshiqi/one-key-cpufriend#3]
<img width="1102" alt="Xnip2019-03-30_17-38-31" src="https://user-images.githubusercontent.com/28970198/55274385-a8eafd00-5312-11e9-9aa4-63259d575696.png">
如图，默认平衡电量模式在不输入直接回车时会报错，看了一下源码，发现没有初始值，可以设置一下默认初始值，检测输入为空时可以使用默认值

**Comment by stevezhengshiqi** [comment]
谢谢反馈！很不错的建议。

**Comment by stevezhengshiqi** [comment]
仔细考虑后还是想要用户自己输入值，毕竟涉及变频参数，脚本不敢擅作主张。
