### ISSUE TITLE
Mac-AA95B1DDAB278B95不被支持

### ISSUE THREAD

**Issue by Z-fly** [stevezhengshiqi/one-key-cpufriend#30]
![image](https://user-images.githubusercontent.com/10470892/113113754-354f9380-923d-11eb-937f-4c0280af11f4.png)

**Comment by Z-fly** [comment]
[Uploading Mac-AA95B1DDAB278B95.plist.zip…]()

**Comment by Z-fly** [comment]
[Mac-AA95B1DDAB278B95.plist.zip](https://github.com/stevezhengshiqi/one-key-cpufriend/files/6235367/Mac-AA95B1DDAB278B95.plist.zip)

**Comment by stevezhengshiqi** [comment]
https://github.com/stevezhengshiqi/one-key-cpufriend/issues/14#issuecomment-731670021

**Comment by Z-fly** [comment]
@stevezhengshiqi 那我手动用ResourceConverter生成的CPUFriendDataProvider是不是根本不起作用？

**Comment by stevezhengshiqi** [comment]
嗯，没有作用，和SMBIOS机型调成iMac19,1效果是一样的。

**Comment by Z-fly** [comment]
> 嗯，没有作用，和SMBIOS机型调成iMac19,1效果是一样的。

那我删掉CPUFriendDataProvider，只留着CPUFriend，CPU变频会正常吗？还是说iMac19.1这个机型根本不需要CPUFriend？

**Comment by Z-fly** [comment]
@stevezhengshiqi

**Comment by stevezhengshiqi** [comment]
光CPUFriend是没有任何效果的，这个驱动本来就不是必需品。5代u之后只要SMBIOS选择了正确的机型并注入了plugintype就能正常变频。
