### ISSUE TITLE
Drop MinKernel in README

### ISSUE THREAD

**Issue by PMheart** [stevezhengshiqi/one-key-cpufriend#32]
As of CPUFriend 1.2.5 the minimum requirement for CPUFriend to load is macOS 10.6.

However as per README,
> The script is only for most 5th-10th generation CPU yet.

making the MinKernel settings meaningless as the lowest supported macOS version for Intel 5th generation is macOS 10.10.

Please just drop MinKernel instead.

Reference: https://github.com/stevezhengshiqi/one-key-cpufriend/issues/26

**Comment by stevezhengshiqi** [comment]
Thanks little cat ^^.
