### ISSUE TITLE
0.8Ghz调度

### ISSUE THREAD

**Issue by vidalouiswang** [stevezhengshiqi/one-key-cpufriend#36]
作者你好，谢谢你开发的脚本，我的CPU是i7 8550U，在Windows下使用电池供电时，大部分时候CPU都保持0.8Ghz频率，package功耗保持在1W左右，使用CPUFriend调整后，很少的时间才能在Intel power gadget中看到CORE MIN到到0.8Ghz，系统请求的大部分时间仍保持1.4~1.5Ghz，package功耗大部分时间仍然保持在2W以上，我想请问如何调整参数才能让使用电池时大部分空闲或轻度任务时保持0.8Ghz，反而是插入电源之后，CORE MIN经常看到0.8, 1.1, 0.5，使用电池供电时开启了低电量模式。因为经过测试现在macOS耗电量比Windows高出1/3，测试项目是在线观看B站1080P视频，使用Chrome浏览器，谢谢。

**Comment by vidalouiswang** [comment]
经过测试，使用电池供电时，关闭低电量模式可以在CORE MIN看到更多的1.0Ghz以下的频率，最低0.4Ghz，但是大部分时候还是1.2Ghz

**Comment by vidalouiswang** [comment]
我尝试过手动修改plist文件生成data provider，在plist文件的Frequencies中枚举了从800到4000的所有频率，步长是1000(1000之后)，但是生成的kext也没有什么作用，关于那些base64编码后的数据我不知道解码后的二进制数据格式，作者有空的话请提供一个这个二进制数据格式的链接给我，谢谢！

**Comment by stevezhengshiqi** [comment]
CPUFriend只能让一些机型的最低频率达到800mhz左右的频率，并不能让机子维持在低频。XCPM是动态的频率调度，我们并不能让机子限制在低频，（macOS下）。

**Comment by vidalouiswang** [comment]
> 

好的，谢谢作者回复，我会再研究一下如何进一步降低功耗。
