### ISSUE TITLE
Script fails with download error when downloading the CPUFriend.kext

### ISSUE THREAD

**Issue by happyharrysco1** [stevezhengshiqi/one-key-cpufriend#38]
Hi There, 

your script now fails when trying to download and extract the cpufriend.kext, it creates the one-key-cpufriend folder on the desktop, it then downloads ResourceConverter.sh, then fails giving the error message to check your connection, but the network on the machine is fine and i can download the CPUFriend release no problem manually

**Comment by stevezhengshiqi** [comment]
Thanks! GitHub uses lazy load now, and the old download logic should be modified. Nice spot!
