### ISSUE TITLE
Macmini8,1机型的board-id说不被支持？

### ISSUE THREAD

**Issue by qinkangdeid** [stevezhengshiqi/one-key-cpufriend#5]
机型是直接选择的右边下拉机型列表选的 参数自动生成需要修改吗 还是？

i5-8400 + 技嘉 z370n-wifi

<img width="881" alt="11111" src="https://user-images.githubusercontent.com/17582522/57977216-58487400-7a26-11e9-9145-96d30c013d82.png">

**Comment by stevezhengshiqi** [comment]
谢谢指出这个问题，已在https://github.com/stevezhengshiqi/one-key-cpufriend/commit/a82bb7b5322f9a0eab00fe06075a249f05d531c2 修复。

**Comment by qinkangdeid** [comment]
多谢 大佬

**Comment by alexylee1101** [comment]
Mac Book Pro 11,1 不支持？
