### ISSUE TITLE
CPU idle frequency cannot get 800ghz

### ISSUE THREAD

**Issue by prajals** [stevezhengshiqi/one-key-cpufriend#7]
I've applied this instructions .but i am only getting idle frequency 1100ghz. i think it should go down 800ghz idle. my cpu is  i7 8750h CPU. need help

**Comment by johnnync13** [comment]
@stevezhengshiqi

**Comment by stevezhengshiqi** [comment]
Not enough information is provided. I need to know board-id and the screenshot of the Terminal when running the script to debug the problem.

**Comment by stevezhengshiqi** [comment]
Close as no response and few information is provided.
