### ISSUE TITLE
hp 440 G5  笔记本使用rehabmanr提供驱动安装后不支持生成。

### ISSUE THREAD

**Issue by aTan20170106** [stevezhengshiqi/one-key-cpufriend#8]
bash -c "$(curl -fsSL https://raw.githubusercontent.com/stevezhengshiqi/one-key-cpufriend/master/one-key-cpufriend_cn.sh)"
  ____   ____    _   _   _____   ____    ___   _____   _   _   ____ 
 / ___| |  _ \  | | | | |  ___| |  _ \  |_ _| | ____| | \ | | |  _ \ 
| |     | |_) | | | | | | |_    | |_) |  | |  |  _|   |  \| | | | | | 
| |___  |  __/  | |_| | |  _|   |  _ <   | |  | |___  | |\  | | |_| | 
 \____| |_|      \___/  |_|     |_| \_\ |___| |_____| |_| \_| |____/ 

你的board-id是 Mac-189A3D4F975D5FFC
信息如上图。
配置是i5 8250u.

**Comment by stevezhengshiqi** [comment]
@aTan20170106 你好，README有写要选择正确的SMBIOS机型。
Mac-189A3D4F975D5FFC对应的机型是MacBookPro11,1，
而根据[Rehabman的仓库](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_HD615_620_630_640_650.plist) i5-8250u(Kabylake-R)要选择机型MacBookPro14,1

**Comment by aTan20170106** [comment]
能加上调整风扇的策略吗？因为有对应的变频，macos的风扇策略比较，要温度高了才去转动。平时还不转了。

**Comment by stevezhengshiqi** [comment]
现代BIOS会自行根据温度和频率来实时调控风扇转速。如果想定制风扇转速，你需要根据DSDT的风扇设备(_HID, "FAN00000")来自行修改。参考样本:https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/blob/master/src/hotpatch/SSDT-FAN-MOD.dsl

因为每台机子的风扇逻辑和DSDT的差异，很难做出一个统一方案放进脚本里。

**Comment by aTan20170106** [comment]
多谢已经解决问题
