### ISSUE TITLE
Does not generate kext after executing the code

### ISSUE THREAD

**Issue by Errrneist** [stevezhengshiqi/one-key-cpufriend#9]
Hi,

I ran your script on macOS 10.15 PB4 and after I executed the code nothing is generated on my desktop. I can see the temp folder being generated (So not an sudo issue) but after the program removed it nothing remains on my desktop. Does your code compatible with 10.15?

Thanks!

Cheers,
Errrneist

**Comment by stevezhengshiqi** [comment]
Hi, I need a screenshot of the terminal to check the output message. Could you help me with that?

**Comment by Errrneist** [comment]
<img width="1413" alt="Screen Shot 2019-08-07 at 3 29 16 PM" src="https://user-images.githubusercontent.com/27667864/62622909-30cbbe00-b928-11e9-830c-58c9d92f91bd.png">

**Comment by stevezhengshiqi** [comment]
I see. Because you choose two system default options, so the script doesn’t do anything.

**Comment by Errrneist** [comment]
> I see. Because you choose two system default options, so the script won’t do anything.
> 
> The system is running in LFM 1300mhz and EPP blance power natively.

Wait so how am I supposed to use this script? Thanks!

**Comment by stevezhengshiqi** [comment]
Choose the options which are not marked as default.

**Comment by Errrneist** [comment]
Great, thanks!

![image](https://user-images.githubusercontent.com/27667864/62625260-835ba900-b92d-11e9-9fba-188c430dc32f.png)
